$(document).ready(function(){
  $(horoscopeForm).submit(function(event){
    event.preventDefault();
    const day = parseInt($("#day").val());
    console.log(day);
    const month = parseInt($("#month").val());
    console.log(month);

    if((month === 3 && day >= 21) || (month === 4 && day <= 19)){
      $("#aries").show();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#taurus").hide();
      console.log("aries");
    }
    else if((month === 4 && day >= 20) || (month === 5 && day <= 20)){
      $("#taurus").show();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("taurus");
    }
    else if((month === 5 && day >= 21 ) || (month === 6 && day <= 21)){
      $("#gemini").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#aries").hide();
      console.log("gemini");
    }
    else if((month === 6 && day >= 22) || (month === 7 && day <= 22)){
      $("#cancer").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("cancer");
    }
    else if((month === 7 && day >= 23) || (month === 8 && day <= 22)){
      $("#leo").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("leo");
    }
    else if((month === 8 && day >=23 ) || (month === 9 && day <= 22)){
      $("#virgo").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("virgo");
    }
    else if((month === 9 && day >= 23) || (month === 10 && day <= 23)){
      $("#libra").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("libra");
    }
    else if((month === 10 && day >= 24) || (month === 11 && day <= 21)){
      $("#scorpio").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("scorpio")
    }
    else if((month === 11 && day >= 22) || (month === 12 && day <= 21)){
      $("#sagittarius").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("sagittarius");
    }
    else if((month === 12 && day >= 22) || (month === 1 && day <= 19)){
      $("#capricorn").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#aquarius").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("capricorn");
    }
    else if((month === 1 && day >= 20) || (month === 2 && day <=18)){
      $("#aquarius").show();
      $("#taurus").hide();
      $("#pisces").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      console.log("aquarius");
    }
    else if((month === 2 && day >= 19) || (month === 3 && day <= 20)){
      $("#pisces").show();
      $("#aquarius").hide();
      $("#capricorn").hide();
      $("#sagittarius").hide();
      $("#scorpio").hide();
      $("#libra").hide();
      $("#virgo").hide();
      $("#leo").hide();
      $("#cancer").hide();
      $("#gemini").hide();
      $("#aries").hide();
      $("#taurus").hide();
      console.log("pisces");
    }
  });
})